package main

// Bridge: browser WebSocket(s) <-> one pgwt-server process (usually behind
// ssh). Trust Milestone T6 hardening:
//
//   - UI-2: request ids are namespaced PER WebSocket connection. The browser
//     generates its own ids (1, 2, 3, ...) so two tabs collide on the shared
//     upstream pipe; the bridge rewrites every outgoing request to a
//     bridge-unique id and rewrites the response back, so a tab can never
//     receive another tab's data.
//   - UI-3: the upstream process is SUPERVISED. When ssh/pgwt-server dies, all
//     pending requests fail fast with a transport error envelope and the
//     process is respawned with capped exponential backoff; requests arriving
//     while it is down get an immediate error instead of a 30 s timeout.
//   - UI-8: response ids are parsed with a strict prefix fast path (the server
//     emits `{"id":N,...` first — an invariant pinned by the integration
//     test) plus a full-JSON fallback for anything else.
//   - UI-12: the WS handshake requires the per-session token (see main.go).
//
// Error envelopes generated BY THE BRIDGE carry "transport":true so the client
// can distinguish "the connection is degraded" from a command-level error
// produced by a healthy server (e.g. the control proxy's "daemon not
// running"). See web/static/lib/transport.js.

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os/exec"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

const (
	requestTimeout = 30 * time.Second
	backoffMin     = 1 * time.Second
	backoffMax     = 30 * time.Second
)

func newUpgrader(token string) websocket.Upgrader {
	return websocket.Upgrader{
		CheckOrigin: func(r *http.Request) bool {
			origin := r.Header.Get("Origin")
			if origin == "" {
				// Non-browser clients (tests, curl): the session token is
				// still required below, so this is not an open door.
				return true
			}
			// Allow localhost origins only (with or without port).
			for _, prefix := range []string{
				"http://localhost",
				"https://localhost",
				"http://127.0.0.1",
				"https://127.0.0.1",
			} {
				if origin == prefix || strings.HasPrefix(origin, prefix+":") {
					return true
				}
			}
			return false
		},
	}
}

// Bridge connects browser WebSockets to a supervised pgwt-server process.
type Bridge struct {
	// factory builds the upstream command (ssh ... pgwt-server ..., or a
	// local pgwt-server in tests). Called on every (re)spawn.
	factory func() *exec.Cmd
	// token is the per-session WS auth token (UI-12); empty disables the check
	// (never in production — main.go always sets one).
	token string
	// clientVersion enables the version handshake (T7 / TST-11): after every
	// (re)spawn the bridge asks the upstream server for its version and warns
	// on stderr when the pair is skewed. Empty disables the check (unit tests
	// that don't care). Warn, never refuse: skew is the normal state.
	clientVersion string
	warnMu        sync.Mutex
	warned        map[string]bool // dedupe identical skew warnings across respawns

	upgrader websocket.Upgrader

	// mu guards the current process handle + stdin writes + `up`.
	mu    sync.Mutex
	cmd   *exec.Cmd
	stdin io.WriteCloser
	up    bool

	// pendMu guards pending + nextID. Keys are bridge-unique ids (never
	// reused), values route the response back to the right connection.
	pendMu  sync.Mutex
	pending map[int64]chan []byte
	nextID  int64

	done      chan struct{} // closed by Close(): stop the supervisor
	closeOnce sync.Once
}

// NewBridge creates a bridge that supervises the command built by factory.
func NewBridge(factory func() *exec.Cmd, token string) *Bridge {
	return &Bridge{
		factory:  factory,
		token:    token,
		upgrader: newUpgrader(token),
		pending:  make(map[int64]chan []byte),
		warned:   make(map[string]bool),
		done:     make(chan struct{}),
	}
}

// NewSSHBridge builds the production factory: ssh to host, run pgwt-server.
// BatchMode prevents interactive password prompts on respawn (a respawn loop
// must never block on a tty); ServerAlive* makes a silently-dead SSH session
// fail within ~30 s instead of hanging forever (UI-3). clientVersion arms the
// version handshake against every spawned server (T7 / TST-11).
func NewSSHBridge(host, serverPath, traceDir, token, clientVersion string) *Bridge {
	b := NewBridge(func() *exec.Cmd {
		return exec.Command("ssh",
			"-o", "BatchMode=yes",
			"-o", "ServerAliveInterval=15",
			"-o", "ServerAliveCountMax=2",
			host, serverPath, traceDir)
	}, token)
	b.clientVersion = clientVersion
	return b
}

// Start spawns the upstream once (synchronously, so startup errors are
// reported) and launches the supervisor that respawns it on death.
func (b *Bridge) Start() error {
	stdout, err := b.spawn()
	if err != nil {
		return err
	}
	go b.supervise(stdout)
	go b.checkServerVersion()
	return nil
}

// Close stops the supervisor and kills the upstream process.
func (b *Bridge) Close() {
	b.closeOnce.Do(func() { close(b.done) })
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.stdin != nil {
		b.stdin.Close()
	}
	if b.cmd != nil && b.cmd.Process != nil {
		b.cmd.Process.Kill()
	}
}

// spawn starts one upstream process and returns its stdout reader.
func (b *Bridge) spawn() (*bufio.Reader, error) {
	cmd := b.factory()
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, fmt.Errorf("stdin pipe: %w", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("stdout pipe: %w", err)
	}
	cmd.Stderr = log.Writer()
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("start: %w", err)
	}
	b.mu.Lock()
	b.cmd = cmd
	b.stdin = stdin
	b.up = true
	b.mu.Unlock()
	// 1MB buffer for large responses.
	return bufio.NewReaderSize(stdout, 1024*1024), nil
}

// supervise reads responses until the upstream dies, then respawns it with
// capped exponential backoff (UI-3). Runs until Close().
func (b *Bridge) supervise(stdout *bufio.Reader) {
	backoff := backoffMin
	for {
		gotAny := b.readLoop(stdout)

		b.mu.Lock()
		b.up = false
		cmd := b.cmd
		b.mu.Unlock()
		if cmd != nil {
			cmd.Wait() // reap
		}
		// Fail everything in flight NOW — the client must see the death
		// within one refresh interval, not after a 30 s timeout.
		b.failAllPending()

		select {
		case <-b.done:
			return
		default:
		}

		if gotAny {
			backoff = backoffMin // the last process worked; restart fresh
		}
		log.Printf("server connection lost; respawning in %v", backoff)
		select {
		case <-b.done:
			return
		case <-time.After(backoff):
		}
		if backoff *= 2; backoff > backoffMax {
			backoff = backoffMax
		}

		var err error
		stdout, err = b.spawn()
		if err != nil {
			log.Printf("respawn failed: %v", err)
			stdout = nil
			continue
		}
		log.Printf("server connection re-established")
		// Re-run the handshake: a respawn may have connected to an upgraded
		// (or downgraded) server binary. Identical warnings are deduped.
		go b.checkServerVersion()
	}
}

// ── Version handshake (T7 / TST-11) ─────────────────────────────────────────

// checkServerVersion asks the upstream server for its version (the `info`
// response carries server_version + protocol since v0.13) and logs a LOUD
// warning on stderr when it differs from this client's build. Warn, never
// refuse — a skewed pair is the normal deployment state; the point is that
// the operator can see it. No-op when the bridge has no client version set.
func (b *Bridge) checkServerVersion() {
	if b.clientVersion == "" {
		return
	}
	line, err := b.roundTrip([]byte(`,"cmd":"info"}`), 10*time.Second)
	if err != nil {
		// The supervisor owns connection-failure reporting; a handshake that
		// cannot complete is not separately alarming.
		return
	}
	var resp struct {
		ServerVersion *string `json:"server_version"`
		Protocol      *int    `json:"protocol"`
	}
	if err := json.Unmarshal(line, &resp); err != nil {
		return
	}
	sv, sp := "", -1
	if resp.ServerVersion != nil {
		sv = *resp.ServerVersion
	}
	if resp.Protocol != nil {
		sp = *resp.Protocol
	}
	if warn := versionSkewWarning(b.clientVersion, protocolRev, sv, sp); warn != "" {
		b.warnMu.Lock()
		seen := b.warned[warn]
		b.warned[warn] = true
		b.warnMu.Unlock()
		if !seen {
			log.Printf("WARNING: %s", warn)
		}
	}
}

// roundTrip sends one bridge-originated request upstream (`tail` is the JSON
// after the id, e.g. `,"cmd":"info"}`) and waits for its response line.
func (b *Bridge) roundTrip(tail []byte, timeout time.Duration) ([]byte, error) {
	b.mu.Lock()
	up, stdin := b.up, b.stdin
	b.mu.Unlock()
	if !up {
		return nil, fmt.Errorf("upstream down")
	}

	ch := make(chan []byte, 1)
	b.pendMu.Lock()
	b.nextID++
	id := b.nextID
	b.pending[id] = ch
	b.pendMu.Unlock()

	msg := append([]byte(`{"id":`+strconv.FormatInt(id, 10)), tail...)
	b.mu.Lock()
	_, werr := fmt.Fprintf(stdin, "%s\n", msg)
	b.mu.Unlock()
	if werr != nil {
		b.pendMu.Lock()
		delete(b.pending, id)
		b.pendMu.Unlock()
		return nil, werr
	}

	select {
	case line, ok := <-ch:
		if !ok {
			return nil, fmt.Errorf("upstream died mid-request")
		}
		return line, nil
	case <-time.After(timeout):
		b.pendMu.Lock()
		delete(b.pending, id)
		b.pendMu.Unlock()
		return nil, fmt.Errorf("timeout")
	}
}

// versionSkewWarning compares client and server versions and returns a
// human-readable warning, or "" when they match. serverVersion=="" /
// serverProto==-1 mean the server did not report them (pre-v0.13 build).
// Pure function — unit-tested directly.
func versionSkewWarning(clientVersion string, clientProto int,
	serverVersion string, serverProto int) string {
	if serverVersion == "" && serverProto == -1 {
		return fmt.Sprintf("version skew: pgwt-server did not report a version "+
			"(build predates the v0.13 handshake); this client is %s (protocol %d). "+
			"Rebuild/redeploy pgwt-server from the same checkout.",
			clientVersion, clientProto)
	}
	if serverProto != clientProto {
		return fmt.Sprintf("PROTOCOL skew: pgwt-server %s speaks protocol %d, "+
			"this client %s expects %d — responses may be misinterpreted. "+
			"Update the older side before trusting what you see.",
			serverVersion, serverProto, clientVersion, clientProto)
	}
	if serverVersion != clientVersion {
		return fmt.Sprintf("version skew: pgwt-server is %s, this client is %s "+
			"(same protocol %d — safe, but behavior/fixes may differ). "+
			"Rebuild/redeploy from the same checkout to align.",
			serverVersion, clientVersion, clientProto)
	}
	return ""
}

// readLoop dispatches upstream JSON lines to pending channels. Returns when
// stdout closes; reports whether any line was read (for backoff reset).
func (b *Bridge) readLoop(stdout *bufio.Reader) bool {
	if stdout == nil {
		return false
	}
	gotAny := false
	for {
		line, err := stdout.ReadBytes('\n')
		if err != nil {
			if len(line) == 0 {
				return gotAny
			}
			// Deliver a final unterminated line before reporting EOF.
		}
		gotAny = true

		id, ok := extractID(line)
		if !ok {
			log.Printf("unparsable server line dropped (%d bytes)", len(line))
			if err != nil {
				return gotAny
			}
			continue
		}
		b.pendMu.Lock()
		ch, exists := b.pending[id]
		if exists {
			delete(b.pending, id)
		}
		b.pendMu.Unlock()
		if exists {
			ch <- line
		}
		if err != nil {
			return gotAny
		}
	}
}

// failAllPending closes every pending channel: the per-request goroutines
// translate that into a transport error envelope for their own client id.
func (b *Bridge) failAllPending() {
	b.pendMu.Lock()
	for id, ch := range b.pending {
		close(ch)
		delete(b.pending, id)
	}
	b.pendMu.Unlock()
}

// transportError builds a bridge-generated error envelope. "transport":true
// tells the client this is a connection-level failure (degraded transport),
// not a command-level error from a healthy server (UI-1).
func transportError(id int64, msg string) []byte {
	return []byte(`{"id":` + strconv.FormatInt(id, 10) +
		`,"error":` + strconv.Quote(msg) + `,"transport":true}`)
}

// HandleWebSocket bridges one browser WebSocket to the upstream server.
func (b *Bridge) HandleWebSocket(w http.ResponseWriter, r *http.Request) {
	// UI-12: require the per-session token before upgrading. See main.go for
	// the threat model.
	if b.token != "" && r.URL.Query().Get("token") != b.token {
		http.Error(w, "missing or invalid session token", http.StatusForbidden)
		return
	}
	conn, err := b.upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Printf("ws upgrade: %v", err)
		return
	}
	defer conn.Close()
	log.Println("Browser connected via WebSocket")

	var wsMu sync.Mutex // serializes conn.WriteMessage
	send := func(msg []byte) {
		wsMu.Lock()
		conn.WriteMessage(websocket.TextMessage, msg)
		wsMu.Unlock()
	}

	for {
		_, msg, err := conn.ReadMessage()
		if err != nil {
			break
		}

		// The id the BROWSER chose — only meaningful within this connection.
		clientID, ok := extractID(msg)
		if !ok {
			send(transportError(0, "malformed request (no id)"))
			continue
		}

		b.mu.Lock()
		up, stdin := b.up, b.stdin
		b.mu.Unlock()
		if !up {
			// Upstream down and respawning: fail fast (UI-3), no 30s stall.
			send(transportError(clientID, "server unavailable (reconnecting)"))
			continue
		}

		// UI-2: allocate a bridge-unique id and register the route BEFORE
		// writing upstream, so the response cannot race the registration.
		ch := make(chan []byte, 1)
		b.pendMu.Lock()
		b.nextID++
		bridgeID := b.nextID
		b.pending[bridgeID] = ch
		b.pendMu.Unlock()

		rewritten, err := rewriteRequestID(msg, bridgeID)
		if err != nil {
			b.pendMu.Lock()
			delete(b.pending, bridgeID)
			b.pendMu.Unlock()
			send(transportError(clientID, "malformed request: "+err.Error()))
			continue
		}

		b.mu.Lock()
		_, werr := fmt.Fprintf(stdin, "%s\n", rewritten)
		b.mu.Unlock()
		if werr != nil {
			b.pendMu.Lock()
			delete(b.pending, bridgeID)
			b.pendMu.Unlock()
			send(transportError(clientID, "server unavailable (reconnecting)"))
			continue
		}

		// Await the response asynchronously so one slow query does not block
		// this connection's other requests.
		go func(clientID, bridgeID int64, ch chan []byte) {
			var resp []byte
			select {
			case line, ok := <-ch:
				if ok {
					resp = rewriteResponseID(line, clientID)
				} else {
					// failAllPending closed us: upstream died mid-request.
					resp = transportError(clientID, "server disconnected")
				}
			case <-time.After(requestTimeout):
				b.pendMu.Lock()
				delete(b.pending, bridgeID)
				b.pendMu.Unlock()
				resp = transportError(clientID, "timeout")
			}
			send(resp)
		}(clientID, bridgeID, ch)
	}
}

// ── JSON id handling (UI-8) ──────────────────────────────────────────────────
//
// Fast path: pgwt-server emits `{"id":N,...}` with the id FIRST (cJSON
// preserves insertion order and every handler adds "id" first) — the
// integration test pins this invariant against the real binary. The browser
// client also serializes {id, cmd, ...} id-first. Anything that does not match
// the strict prefix goes through a full JSON parse; substring scanning (which
// could match an "id" anywhere in the payload) is never used.

// extractID returns the envelope id of a JSON request/response line.
func extractID(data []byte) (int64, bool) {
	if id, rest := idFirstPrefix(data); rest >= 0 {
		return id, true
	}
	// Fallback: full parse (uses json.Number so huge ids survive).
	var env struct {
		ID json.Number `json:"id"`
	}
	if err := json.Unmarshal(data, &env); err != nil {
		return 0, false
	}
	id, err := env.ID.Int64()
	if err != nil {
		return 0, false
	}
	return id, true
}

// idFirstPrefix strictly matches `{"id":<int>` at the start of the line
// (allowing leading whitespace). Returns the id and the offset just past the
// integer, or offset -1 on no match.
func idFirstPrefix(data []byte) (int64, int) {
	i := 0
	for i < len(data) && (data[i] == ' ' || data[i] == '\t' || data[i] == '\r' || data[i] == '\n') {
		i++
	}
	prefix := []byte(`{"id":`)
	if !bytes.HasPrefix(data[i:], prefix) {
		return 0, -1
	}
	i += len(prefix)
	for i < len(data) && data[i] == ' ' {
		i++
	}
	start := i
	if i < len(data) && data[i] == '-' {
		i++
	}
	digits := i
	for i < len(data) && data[i] >= '0' && data[i] <= '9' {
		i++
	}
	if i == digits {
		return 0, -1 // no digits (e.g. a string id)
	}
	n, err := strconv.ParseInt(string(data[start:i]), 10, 64)
	if err != nil {
		return 0, -1
	}
	return n, i
}

// rewriteRequestID replaces the request's id with the bridge id. Requests are
// small and come from our own client (id-first), so try surgery first and fall
// back to a json.Number-preserving re-marshal (never float64 — the ns
// timestamps in "from"/"to" exceed 2^53 and must not lose precision).
func rewriteRequestID(msg []byte, newID int64) ([]byte, error) {
	if out, ok := spliceID(msg, newID); ok {
		return out, nil
	}
	dec := json.NewDecoder(bytes.NewReader(msg))
	dec.UseNumber()
	var m map[string]interface{}
	if err := dec.Decode(&m); err != nil {
		return nil, err
	}
	if _, ok := m["id"]; !ok {
		return nil, fmt.Errorf("no id field")
	}
	m["id"] = json.Number(strconv.FormatInt(newID, 10))
	return json.Marshal(m)
}

// rewriteResponseID maps the upstream response's bridge id back to the id the
// client sent. Responses can be large; the id-first invariant makes this a
// cheap prefix splice. If the prefix doesn't match we still deliver the line
// with a best-effort re-marshal; on total failure the caller's line is
// returned unchanged (the client will drop the unknown id rather than
// mis-deliver).
func rewriteResponseID(line []byte, clientID int64) []byte {
	if out, ok := spliceID(line, clientID); ok {
		return out
	}
	dec := json.NewDecoder(bytes.NewReader(line))
	dec.UseNumber()
	var m map[string]interface{}
	if err := dec.Decode(&m); err != nil {
		return line
	}
	m["id"] = json.Number(strconv.FormatInt(clientID, 10))
	if out, err := json.Marshal(m); err == nil {
		return out
	}
	return line
}

// spliceID swaps the integer in an id-first envelope for newID.
func spliceID(data []byte, newID int64) ([]byte, bool) {
	_, end := idFirstPrefix(data)
	if end < 0 {
		return nil, false
	}
	// Everything before the integer is `{"id":` (plus whitespace) — rebuild.
	out := make([]byte, 0, len(data)+20)
	out = append(out, `{"id":`...)
	out = strconv.AppendInt(out, newID, 10)
	out = append(out, bytes.TrimRight(data[end:], "\n")...)
	return out, true
}
