package main

// Bridge tests (Trust Milestone T6, UI-7).
//
// Unit tests cover the id parsing/rewriting invariants (UI-8) with no
// external dependencies. The integration tests spawn the REAL pgwt-server
// (built by `make pgwt-server`) over a local pipe — no SSH — against a
// synthetic trace directory generated by tests/gen_test_traces, and drive the
// bridge end-to-end through a real WebSocket:
//
//   - normal request/response through the id-rewriting path
//   - two concurrent connections issuing the SAME ids never exchange data
//     (UI-2 regression)
//   - killing the server mid-request delivers an error envelope with
//     "transport":true (UI-1), and the bridge respawns the server with
//     backoff so a later request succeeds (UI-3)
//   - the WS handshake requires the session token (UI-12)
//   - the server's id-first envelope invariant (`{"id":N,...`) that the
//     bridge's fast path relies on (UI-8)
//
// Run locally: (cd web && go test ./...) after `make pgwt-server &&
// make -C tests gen_test_traces`. Without the binaries the integration tests
// skip; CI sets PGWT_BRIDGE_TEST_REQUIRE=1 to turn a skip into a failure.

import (
	"bufio"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/gorilla/websocket"
)

// ── Unit tests: id parsing / rewriting (UI-8) ────────────────────────────────

func TestExtractIDFastPath(t *testing.T) {
	cases := []struct {
		line string
		id   int64
		ok   bool
	}{
		{`{"id":42,"cmd":"info"}`, 42, true},
		{`{"id": 7,"rows":[]}`, 7, true},
		{`  {"id":-3,"error":"x"}`, -3, true},
		{`{"id":9007199254740993,"x":1}`, 9007199254740993, true}, // > 2^53
	}
	for _, c := range cases {
		id, ok := extractID([]byte(c.line))
		if ok != c.ok || id != c.id {
			t.Errorf("extractID(%q) = (%d,%v), want (%d,%v)", c.line, id, ok, c.id, c.ok)
		}
	}
}

func TestExtractIDFallbackParsesFullJSON(t *testing.T) {
	// id NOT first: the strict prefix fails, the JSON fallback must succeed —
	// and must never be fooled by an "id" substring inside a value.
	id, ok := extractID([]byte(`{"cmd":"x","payload":"\"id\":999","id":5}`))
	if !ok || id != 5 {
		t.Fatalf("fallback extractID = (%d,%v), want (5,true)", id, ok)
	}
	if _, ok := extractID([]byte(`not json at all`)); ok {
		t.Fatal("garbage line must not yield an id")
	}
	if _, ok := extractID([]byte(`{"cmd":"x"}`)); ok {
		t.Fatal("missing id must not yield an id")
	}
}

func TestRewriteRequestIDPreservesNanosecondPrecision(t *testing.T) {
	// from/to are ns timestamps > 2^53: a float64 round-trip would corrupt
	// them. The rewritten request must contain the exact digit strings.
	msg := []byte(`{"id":3,"cmd":"aas","from":1774000000000000001,"to":1774000000000000999}`)
	out, err := rewriteRequestID(msg, 42)
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	for _, want := range []string{`"id":42`, `1774000000000000001`, `1774000000000000999`} {
		if !strings.Contains(s, want) {
			t.Errorf("rewritten request %q missing %q", s, want)
		}
	}
	// Same guarantee on the fallback path (id not first).
	out, err = rewriteRequestID([]byte(`{"cmd":"aas","from":1774000000000000001,"id":3}`), 42)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), `1774000000000000001`) {
		t.Errorf("fallback rewrite lost precision: %s", out)
	}
	id, ok := extractID(out)
	if !ok || id != 42 {
		t.Errorf("fallback rewrite id = (%d,%v), want (42,true)", id, ok)
	}
}

func TestRewriteResponseID(t *testing.T) {
	out := rewriteResponseID([]byte(`{"id":900001,"rows":[{"id":123}]}`+"\n"), 7)
	s := string(out)
	if !strings.HasPrefix(s, `{"id":7,`) {
		t.Errorf("response not rewritten id-first: %s", s)
	}
	if !strings.Contains(s, `{"id":123}`) {
		t.Errorf("inner id mangled: %s", s)
	}
}

// ── Integration harness ──────────────────────────────────────────────────────

func requireIntegration(t *testing.T) (serverBin, traceDir string) {
	t.Helper()
	serverBin, err := filepath.Abs("../pgwt-server")
	if err != nil {
		t.Fatal(err)
	}
	genBin, err := filepath.Abs("../tests/gen_test_traces")
	if err != nil {
		t.Fatal(err)
	}
	for _, bin := range []string{serverBin, genBin} {
		if _, err := os.Stat(bin); err != nil {
			if os.Getenv("PGWT_BRIDGE_TEST_REQUIRE") != "" {
				t.Fatalf("required binary missing: %s (build with make)", bin)
			}
			t.Skipf("binary missing: %s (build with `make pgwt-server` / `make -C tests gen_test_traces`)", bin)
		}
	}

	// Tiny synthetic scenario (same shape as tests/server_harness.py):
	// one backend alternating IO:DataFileRead (0x0A000015) and CPU.
	const base = 10_000_000_000_000
	scenario := fmt.Sprintf(`{
		"backends": [{"pid": 1000, "type": "client", "user": "u", "db": "d"}],
		"queries":  [{"id": 100, "text": "SELECT 1"}],
		"events": [
			{"pid":1000,"ts":%d,"dur":5000000,"old":167772181,"new":0,"qid":100},
			{"pid":1000,"ts":%d,"dur":8000000,"old":0,"new":167772181,"qid":100},
			{"pid":1000,"ts":%d,"dur":4000000,"old":167772181,"new":0,"qid":100}
		]
	}`, base+5_000_000, base+13_000_000, base+17_000_000)

	traceDir = t.TempDir()
	cmd := exec.Command(genBin, "-o", traceDir, "--inline", scenario)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("gen_test_traces: %v\n%s", err, out)
	}
	return serverBin, traceDir
}

// testBridge starts a bridge whose upstream is a real local pgwt-server, plus
// an httptest server for the WS endpoint. `procCh` receives each spawned
// process so tests can kill it.
func testBridge(t *testing.T, token string) (*httptest.Server, *Bridge, chan *exec.Cmd) {
	t.Helper()
	serverBin, traceDir := requireIntegration(t)
	procCh := make(chan *exec.Cmd, 8)
	b := NewBridge(func() *exec.Cmd {
		cmd := exec.Command(serverBin, traceDir)
		procCh <- cmd
		return cmd
	}, token)
	if err := b.Start(); err != nil {
		t.Fatalf("bridge start: %v", err)
	}
	srv := httptest.NewServer(http.HandlerFunc(b.HandleWebSocket))
	t.Cleanup(func() {
		srv.Close()
		b.Close()
	})
	return srv, b, procCh
}

func wsURL(srv *httptest.Server, token string) string {
	u := "ws" + strings.TrimPrefix(srv.URL, "http")
	if token != "" {
		u += "?token=" + token
	}
	return u
}

func dial(t *testing.T, srv *httptest.Server, token string) *websocket.Conn {
	t.Helper()
	conn, _, err := websocket.DefaultDialer.Dial(wsURL(srv, token), nil)
	if err != nil {
		t.Fatalf("ws dial: %v", err)
	}
	t.Cleanup(func() { conn.Close() })
	return conn
}

func roundTrip(t *testing.T, conn *websocket.Conn, req string) map[string]json.RawMessage {
	t.Helper()
	if err := conn.WriteMessage(websocket.TextMessage, []byte(req)); err != nil {
		t.Fatalf("ws write: %v", err)
	}
	conn.SetReadDeadline(time.Now().Add(10 * time.Second))
	_, resp, err := conn.ReadMessage()
	if err != nil {
		t.Fatalf("ws read: %v", err)
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(resp, &m); err != nil {
		t.Fatalf("bad response JSON %q: %v", resp, err)
	}
	return m
}

func idOf(t *testing.T, m map[string]json.RawMessage) int64 {
	t.Helper()
	var n json.Number
	if err := json.Unmarshal(m["id"], &n); err != nil {
		t.Fatalf("response id: %v", err)
	}
	id, _ := n.Int64()
	return id
}

// ── Integration tests ────────────────────────────────────────────────────────

func TestBridgeNormalRequestResponse(t *testing.T) {
	srv, _, _ := testBridge(t, "tok123")
	conn := dial(t, srv, "tok123")

	m := roundTrip(t, conn, `{"id":7,"cmd":"info"}`)
	if got := idOf(t, m); got != 7 {
		t.Errorf("response id = %d, want the client's id 7", got)
	}
	if _, ok := m["error"]; ok {
		t.Fatalf("unexpected error: %s", m["error"])
	}
	if _, ok := m["num_cpus"]; !ok {
		t.Errorf("info response missing num_cpus: %v", m)
	}
}

func TestBridgeCommandErrorIsNotTransport(t *testing.T) {
	// A server-side command error must pass through WITHOUT the bridge's
	// transport flag — the client uses that flag to detect a dead pipe.
	srv, _, _ := testBridge(t, "tok123")
	conn := dial(t, srv, "tok123")
	m := roundTrip(t, conn, `{"id":9,"cmd":"definitely_not_a_command"}`)
	if _, ok := m["error"]; !ok {
		t.Fatalf("expected an error envelope, got %v", m)
	}
	if _, ok := m["transport"]; ok {
		t.Errorf("command-level error must not carry transport:true: %v", m)
	}
	if got := idOf(t, m); got != 9 {
		t.Errorf("error envelope id = %d, want 9", got)
	}
}

// UI-2 regression: two connections using the SAME request ids concurrently
// must each receive their own responses.
func TestBridgeTwoConnectionsSameIDsNeverExchangeData(t *testing.T) {
	srv, _, _ := testBridge(t, "tok123")
	connA := dial(t, srv, "tok123")
	connB := dial(t, srv, "tok123")

	const rounds = 40
	var wg sync.WaitGroup
	errs := make(chan error, 2*rounds)

	// A always asks `info` (distinctive field: num_cpus); B always asks
	// `top_events` (distinctive field: rows). Same id on both, every round.
	run := func(conn *websocket.Conn, cmd, wantField, otherField string) {
		defer wg.Done()
		for i := 1; i <= rounds; i++ {
			req := fmt.Sprintf(`{"id":%d,"cmd":"%s","from":9000000000000,"to":11000000000000}`, i, cmd)
			if err := conn.WriteMessage(websocket.TextMessage, []byte(req)); err != nil {
				errs <- err
				return
			}
			conn.SetReadDeadline(time.Now().Add(10 * time.Second))
			_, resp, err := conn.ReadMessage()
			if err != nil {
				errs <- err
				return
			}
			var m map[string]json.RawMessage
			if err := json.Unmarshal(resp, &m); err != nil {
				errs <- err
				return
			}
			var n json.Number
			json.Unmarshal(m["id"], &n)
			if n.String() != fmt.Sprint(i) {
				errs <- fmt.Errorf("%s round %d: got id %s", cmd, i, n)
				return
			}
			if _, ok := m[wantField]; !ok {
				errs <- fmt.Errorf("%s round %d: missing %q (cross-tab data mixup?): %s",
					cmd, i, wantField, resp)
				return
			}
			if _, ok := m[otherField]; ok {
				errs <- fmt.Errorf("%s round %d: got the OTHER connection's field %q: %s",
					cmd, i, otherField, resp)
				return
			}
		}
	}
	wg.Add(2)
	go run(connA, "info", "num_cpus", "rows")
	go run(connB, "top_events", "rows", "num_cpus")
	wg.Wait()
	close(errs)
	for err := range errs {
		t.Error(err)
	}
}

// UI-1 + UI-3: killing the server mid-request produces a transport error
// envelope (not silence, not a 30 s stall), and the bridge respawns the
// server so a later request succeeds without restarting the client.
func TestBridgeUpstreamDeathErrorEnvelopeAndRespawn(t *testing.T) {
	srv, _, procCh := testBridge(t, "tok123")
	proc1 := <-procCh
	conn := dial(t, srv, "tok123")

	// Sanity: server answers.
	m := roundTrip(t, conn, `{"id":1,"cmd":"info"}`)
	if _, ok := m["error"]; ok {
		t.Fatalf("precondition failed: %s", m["error"])
	}

	// Freeze the server so the next request stays pending, then kill it:
	// the pending request MUST fail with a transport error envelope.
	if err := proc1.Process.Signal(syscall.SIGSTOP); err != nil {
		t.Fatal(err)
	}
	if err := conn.WriteMessage(websocket.TextMessage,
		[]byte(`{"id":2,"cmd":"info"}`)); err != nil {
		t.Fatal(err)
	}
	time.Sleep(200 * time.Millisecond) // let the request reach the (stopped) pipe
	proc1.Process.Kill()               // SIGKILL also clears the pending SIGSTOP

	conn.SetReadDeadline(time.Now().Add(10 * time.Second))
	_, resp, err := conn.ReadMessage()
	if err != nil {
		t.Fatalf("expected an error envelope for the mid-request death: %v", err)
	}
	var env struct {
		ID        int64  `json:"id"`
		Error     string `json:"error"`
		Transport bool   `json:"transport"`
	}
	if err := json.Unmarshal(resp, &env); err != nil {
		t.Fatalf("bad envelope %q: %v", resp, err)
	}
	if env.ID != 2 || env.Error == "" || !env.Transport {
		t.Fatalf("mid-request death envelope = %s, want id=2, error set, transport:true", resp)
	}

	// Requests during the outage fail FAST with a transport envelope.
	m = roundTrip(t, conn, `{"id":3,"cmd":"info"}`)
	if _, ok := m["error"]; !ok {
		// The respawn may have already completed (1 s backoff) — that is
		// fine; the fast-fail path is only reachable while it is down.
		t.Logf("request 3 already succeeded (respawn was fast)")
	}

	// UI-3: the bridge respawns the server; within a few seconds a request
	// must succeed again on the SAME client connection.
	deadline := time.Now().Add(15 * time.Second)
	for {
		m = roundTrip(t, conn, `{"id":4,"cmd":"info"}`)
		if _, ok := m["error"]; !ok {
			break // recovered
		}
		if time.Now().After(deadline) {
			t.Fatalf("bridge did not respawn the server in time; last: %v", m)
		}
		time.Sleep(500 * time.Millisecond)
	}
	if _, ok := m["num_cpus"]; !ok {
		t.Errorf("post-respawn info response malformed: %v", m)
	}
}

// UI-12: the WS handshake requires the session token.
func TestBridgeRequiresSessionToken(t *testing.T) {
	srv, _, _ := testBridge(t, "sekrit")

	if _, resp, err := websocket.DefaultDialer.Dial(wsURL(srv, ""), nil); err == nil {
		t.Fatal("dial without token must fail")
	} else if resp == nil || resp.StatusCode != http.StatusForbidden {
		t.Errorf("expected 403, got %v", resp)
	}
	if _, resp, err := websocket.DefaultDialer.Dial(wsURL(srv, "wrong"), nil); err == nil {
		t.Fatal("dial with wrong token must fail")
	} else if resp == nil || resp.StatusCode != http.StatusForbidden {
		t.Errorf("expected 403, got %v", resp)
	}
	conn := dial(t, srv, "sekrit") // correct token connects
	m := roundTrip(t, conn, `{"id":1,"cmd":"info"}`)
	if _, ok := m["error"]; ok {
		t.Fatalf("token-authed request failed: %s", m["error"])
	}
}

// UI-8: pin the id-first envelope invariant against the REAL server — the
// bridge's response fast path depends on it. If the server ever stops
// emitting `{"id":N,...` first, this fails loudly instead of silently
// falling back to full-JSON parsing on every (potentially huge) response.
func TestServerEmitsIDFirstInvariant(t *testing.T) {
	serverBin, traceDir := requireIntegration(t)
	cmd := exec.Command(serverBin, traceDir)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		t.Fatal(err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatal(err)
	}
	if err := cmd.Start(); err != nil {
		t.Fatal(err)
	}
	defer func() { stdin.Close(); cmd.Process.Kill(); cmd.Wait() }()

	r := bufio.NewReaderSize(stdout, 1024*1024)
	// Data responses, error responses, and the control proxy: ALL must be
	// id-first.
	requests := []string{
		`{"id":11,"cmd":"info"}`,
		`{"id":12,"cmd":"time_model","from":9000000000000,"to":11000000000000}`,
		`{"id":13,"cmd":"no_such_command"}`,
		`{"id":14,"cmd":"control","request":{"cmd":"status"}}`,
	}
	for _, req := range requests {
		fmt.Fprintf(stdin, "%s\n", req)
		line, err := r.ReadBytes('\n')
		if err != nil {
			t.Fatalf("server closed on %q: %v", req, err)
		}
		id, end := idFirstPrefix(line)
		if end < 0 {
			t.Errorf("response to %q is not id-first: %.80s", req, line)
			continue
		}
		wantID, _ := extractID([]byte(req))
		if id != wantID {
			t.Errorf("response id %d != request id %d for %q", id, wantID, req)
		}
	}
}
